[package]
name = "ev3dev-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
fixed = "1.29.0"
scopeguard = "1.2.0"
tokio = {version = "1.48.0", features = ["time"]}


[profile.release]
lto = true
strip = true
opt-level = "s"
