[package]
name = "ev3dev-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
pid = "4.0.0"
scopeguard = "1.2.0"
smol = "2.0.2"
tokio = {version = "1.48.0", features = ["macros", "rt", "rt-multi-thread"]}


[profile.release]
lto = true
strip = true
opt-level = "s"
